# You can safely delete this file to disable welcome page
ezplatform:
    system:
        site:
            content_view:
                full:
                    aboutUs:
                        template: "@ezdesign/full/about.html.twig"
                        match:
                            Id\Location: 55
                    contactUs:
                        template: "@ezdesign/full/contact.html.twig"
                        match:
                            Id\Location: 56
                    home:
                        template: "@ezdesign/full/home.html.twig"
                        match:
                            Identifier\ContentType: home
                    event:
                        template: "@ezdesign/full/event.html.twig"
                        match:
                            Identifier\ContentType: event













