ezplatform:
    system:
        site:
            content_view:
                full:
                    about Us:
                        template: "@ezdesign/full/about.html.twig"
                        match:
                            Identifier\ContentType: about_us
                    the_knowledge_serie	:
                        controller: App\Controller\FolderController::showAction
                        template: "@ezdesign/full/knowledge-series.html.twig"
                        match:
                            Identifier\ContentType: the_knowledge_serie
                    home:
                        controller: App\Controller\FolderController::homeAction
                        template: "@ezdesign/full/home.html.twig"
                        match:
                            Identifier\ContentType: home
                    events:
                        controller: App\Controller\FolderController::showAction
                        template: "@ezdesign/full/event.html.twig"
                        match:
                            Identifier\ContentType: myfolder
                    category:
                        controller: App\Controller\FolderController::showAction
                        template: "@ezdesign/full/category.html.twig"
                        match:
                            Identifier\ContentType: myfolder
                    contact Us:
                        template: "@ezdesign/full/contact.html.twig"
                        match:
                            Identifier\ContentType: contact_us
                    member:
                        template: "@ezdesign/full/member-registration.html.twig"
                        match:
                            Identifier\ContentType: member
                    login:
                        template: "@ezdesign/full/member-login.html.twig"
                        match:
                            Identifier\ContentType: login
