ezplatform:
    system:
        site:
            content_view:
                full:
                    aboutUs:
                        template: "@ezdesign/full/about.html.twig"
                        match:
                            Id\Location: 55
                    contactUs:
                        template: "@ezdesign/full/contact.html.twig"
                        match:
                            Id\Location: 56
                    the_knowledge_serie	:
                        controller: App\Controller\FolderController::showAction
                        template: "@ezdesign/full/knowledge-series.html.twig"
                        match:
                            Identifier\ContentType: the_knowledge_serie
                    home:
                        controller: App\Controller\FolderController::homeAction
                        template: "@ezdesign/full/home.html.twig"
                        match:
                            Identifier\ContentType: home
                    event:
                        template: "@ezdesign/full/event.html.twig"
                        match:
                            Identifier\ContentType: event