ezplatform:
    system:
        site:
            content_view:
                full:
                    about Us:
                        template: "@ezdesign/full/about.html.twig"
                        match:
                            Identifier\ContentType: about_us
                    the_knowledge_serie	:
                        controller: App\Controller\FolderController::showAction
                        template: "@ezdesign/full/knowledge-series.html.twig"
                        match:
                            Identifier\ContentType: the_knowledge_serie
                    home:
                        controller: App\Controller\FolderController::homeAction
                        template: "@ezdesign/full/home.html.twig"
                        match:
                            Identifier\ContentType: home
                    events:
                        controller: App\Controller\FolderController::showAction
                        template: "@ezdesign/full/event.html.twig"
                        match:
                            Id\Location: 132
                    category:
                        controller: App\Controller\FolderController::showAction
                        template: "@ezdesign/full/category.html.twig"
                        match:
                            Id\Location: 142
                    contact Us:
                        template: "@ezdesign/full/contact.html.twig"
                        match:
                            Identifier\ContentType: contact_us
                    galleries:
                        controller: App\Controller\FolderController::showAction
                        template: "@ezdesign/full/gallery.html.twig"
                        match:
                            Id\Location: 151
