parameters:
    locale: 'en'
    ezsettings.default.security.login_template: "@@ezdesign/full/member-login.html.twig"

services:
    app.criteria.children:
        class: App\Criteria\Children

    App\Controller\FolderController:
        class: App\Controller\FolderController
        arguments:
            - '@ezpublish.api.service.search'
            - '@ezpublish.config.resolver'
            - '@app.criteria.children'
        tags:
            - { name: controller.service_arguments }